name: Samson Stannus
markdown: kramdown
highlighter: pygments
url: samsonstannus.us
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
permalink: /blog/:year/:month/:day/:title
